-- CreateEnum
CREATE TYPE "PickPhase" AS ENUM ('CAPTAIN_FREEPICK', 'PHASED_PICK', 'SCRAMBLE', 'RANDOM');

-- AlterTable
ALTER TABLE "Scrim" ADD COLUMN "pickPhase" "PickPhase" NOT NULL DEFAULT 'CAPTAIN_FREEPICK';
